### ISSUE TITLE
rePort : problème avec les plages temporelles

### ISSUE THREAD

**Issue by ThomasLaurentInsee** [InseeFr/disaggR#56]
Dans rePort, lorsqu'on crée les modèles presets (l. 16 de report.Rmd), on ne récupère pas les paramètres de dates. Du coup, si les séries hfserie et lfserie sont définies sur une plage plus large, les modèles générés ne correspondent pas et éventuellement il y a une erreur si les plages hf et lf ne sont pas concordantes (ce qui est souvent le cas).

Il suffi d'ajouter ces dates aux paramètres récupérés de model.list l.16

**Comment by arnaud-feldmann** [comment]
Salut Thomas,

Peux-tu donner un exemple avec le résultat escompté ?

Merci.

**Comment by arnaud-feldmann** [comment]
Si tu t'en occupes @ThomasLaurentInsee n'oublie pas de vérifier que reView a un comportement cohérent avec rePort.

Essaie de faire le merge après une pull request, comme ça tu as le hashtag qui va bien et on peut faire un fichier news propre comme j'essaie de commencer à faire ^^

rePort j'avoue j'ai pas fait de test unitaire interne car c'est un peu chiant mais on peut réfléchir à ça.

Merci en tt cas et bon we !

**Comment by arnaud-feldmann** [comment]
Tu as raison mon usage de presets_list_fun est incohérent avec reView dans rePort. J'ai oublié des paramètres.

**Comment by ThomasLaurentInsee** [comment]
Un exemple reproductible très simple :
```
turnover_2001 <- window(turnover, start = 2001)

bn <- twoStepsBenchmark(turnover_2001, construction,
                        start.domain = 2001,
                        start.coeff.calc = 2001,
                        start.benchmark = 2001)

rePort(bn)

```

Le cas est assez fréquent dans Ariege car les données annuelles sont souvent définis sur une plage plus large que les indicateurs.
