### ISSUE TITLE
problème dans l'onglet "Export" de reView suite aux derniers changements

### ISSUE THREAD

**Issue by FanchMorvan** [InseeFr/disaggR#87]
Suite aux derniers changements, et en particulier à la transformation des variables `hfserie_name` et `lfserie_name` en expressions dans reView, la fonction [get_benchmark_call ](https://github.com/InseeFr/disaggR/blob/9b2fd4fbe5e78843f38750da2b17736f55a1bcad/R/reView.R#L387) ne fonctionne plus comme on l'attends.

Le passage d'un `call` à un `character` ne se fait visiblement pas comme on pourrait le penser intuitivement, ce qui donne un résultat non attendu dans des cas je penses assez courant. Un petit exemple ci-dessous :

```
> a.p3m_faz1_3 <- Deverse("a.p3m_faz1_3")
> a.p3m_gc10div_3 <- Deverse("a.p3m_gc10div_3")
> res <- reView(twoStepsBenchmark(Deverse("mc.p41_gc10div_2_alim"), a.p3m_faz1_3 + a.p3m_gc10div_3, TRUE, FALSE, NULL, NULL, 1980, 1991, 1978, 1991, 1978, 1992.99, NULL))
```

Donne la sortie suivante dans l'onglet "Export" de reView :

![image](https://user-images.githubusercontent.com/124688886/218467655-c905c243-ab6e-4520-b89d-8c57b6c59fc4.png)

Pour transformer un objet de classe `call` en un `character`, j'ai trouvé le code suivant :
```
char_appel <- capture.output(print(call_appel))
```
Il doit certainement exister des façons plus propres de faire ça... Ce ne devrait en tout cas pas être trop compliqué à régler.

**Comment by FanchMorvan** [comment]
Bon j'ai finalement trouvé la façon propre de le faire : c'est simplement avec `deparse`...

**Comment by arnaud-feldmann** [comment]
Oui en effet, j'ai pas beaucoup de temps alors je fais les commit rapidement.

Mais dès lors que hfserie_name et lfserie_name sont requis sous forme de character, il faut deparse comme j'ai fait à d'autres endroits. Je viens de passer le commit (sans checker). Si tu vois un autre bug ou oubli n'hésite pas. Bonne journée.
